---@alias BuildType
---| "DebugGame"
---| "Development"
---| "Shipping"

--- The options for UnrealEngine.nvim
---@class Opts
---@field engine_path string|table<string>|nil The path/s to the source version of Unreal Engine
---@field build_type BuildType|nil The type of build
---@field with_editor boolean|nil If you are also building the editor
---@field platform string|nil The Unreal Engine platform - Will be set automatically if not specified
---@field register_icon boolean|nil Registers the Unreal Engine icon for .uproject files
---@field close_on_success boolean|nil Close the terminal split automatically when the command is successful
---@field uproject_path string|nil Used when calling from external sources like mbwilding/launcher.nvim
---@field auto_generate boolean|nil Will generate the LSP info if .uproject is detected at top level of cwd
---@field auto_build boolean|nil Will build your C++ code on save

--- Information about the project
--- @class UprojectInfo
--- @field path string Full path to the .uproject file
--- @field name string The project name derived from the file name (without extension)
--- @field cwd string The projects current working directory
